version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'db'
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - "postgres"
    links:
      - "postgres"
    environment:
      DB_PASSWORD: 'password'
      DB_USER: 'app'
      DB_NAME: 'db'
      DB_HOST: 'postgres'
      PORT: 8080
    ports:
      - '8080:8080'
    command: npm start
